'----------------------------------------------------------------------------
'   Generated: SwinGame header file wrapper code for C#
'----------------------------------------------------------------------------
'
' Generated by SGWrapperGen - DO NOT EDIT!
'
' SwinGame wrapper for C#
'
' Links with the SGSDK library (SGSDK.dll, libSGSDK.so, or SGSDK.framework)
'
'----------------------------------------------------------------------------

import System
import System.Text
import System.Runtime.InteropServices
import Color = System.Drawing.Color

Namespace SwinGame

%(library_code)s

End Namespace
