#!/bin/bash

#
# Declares the base template and dist directories for Swingame
# distributions.
#

SWINGAME_DIR="${APP_PATH}/../../"
SWINGAME_DIR=`cd "$SWINGAME_DIR"; pwd`

PYTHON_SCRIPT_DIR=${SWINGAME_DIR}/Tools/SGWrapperGen

TEMPLATE_DIR="${SWINGAME_DIR}/Templates"
DIST_DIR="${SWINGAME_DIR}/Dist"

COMMON_TEMPLATE_DIR="${TEMPLATE_DIR}/Common"

TMP_DIR=${SWINGAME_DIR}/tmp

# 
# Directories related to C
# 
C_TEMPLATE_DIR="${TEMPLATE_DIR}/C"
C_DIST_DIR="${DIST_DIR}/C"

COMMON_C_TEMPLATE_DIR="${C_TEMPLATE_DIR}/common"

GCC_C_TEMPLATE_DIR="${C_TEMPLATE_DIR}/gcc"
GCC_C_DIST_DIR="${C_DIST_DIR}/gcc"

XCODE_C_TEMPLATE_DIR="${C_TEMPLATE_DIR}/xcode 3"
XCODE_C_DIST_DIR="${C_DIST_DIR}/xcode 3"

CODEBLOCKS_C_TEMPLATE_DIR="${C_TEMPLATE_DIR}/code blocks"
CODEBLOCKS_C_DIST_DIR="${C_DIST_DIR}/code blocks/SwinGame"

# 
# Directories related to Objective C
# 
OBJC_TEMPLATE_DIR="${TEMPLATE_DIR}/ObjC"
OBJC_DIST_DIR="${DIST_DIR}/ObjC"

COMMON_OBJC_TEMPLATE_DIR="${OBJC_TEMPLATE_DIR}/common"

XCODE_OBJC_TEMPLATE_DIR="${OBJC_TEMPLATE_DIR}/xcode 3"
XCODE_OBJC_DIST_DIR="${OBJC_DIST_DIR}/xcode 3"

GCC_OBJC_TEMPLATE_DIR="${OBJC_TEMPLATE_DIR}/gcc"
GCC_OBJC_DIST_DIR="${OBJC_DIST_DIR}/gcc"

#
# Directories related to C#
#
CS_TEMPLATE_DIR="${TEMPLATE_DIR}/CSharp"
CS_DIST_DIR="${DIST_DIR}/CSharp"

COMMON_CS_TEMPLATE_DIR="${CS_TEMPLATE_DIR}/Common"

MONO_TEMPLATE_DIR="${CS_TEMPLATE_DIR}/Mono"
MONO_DIST_DIR="${CS_DIST_DIR}/Mono"

VS05_TEMPLATE_DIR="${CS_TEMPLATE_DIR}/VS05"
VS05_DIST_DIR="${CS_DIST_DIR}/VS05"

VS08_TEMPLATE_DIR="${CS_TEMPLATE_DIR}/VS08"
VS08_DIST_DIR="${CS_DIST_DIR}/VS08"

STUDIO_TEMPLATE_DIR="${TEMPLATE_DIR}/Visual Studio"
STUDIO_DIST_DIR="${DIST_DIR}/Visual Studio"

STUDIO_EX_CS_08_TEMP_DIR="${STUDIO_TEMPLATE_DIR}/Express C# 08"
STUDIO_EX_CS_08_DIST_DIR="${STUDIO_DIST_DIR}/Express C# 08"

#
# Directories related to Pascal
#
PAS_TEMPLATE_DIR="${TEMPLATE_DIR}/Pascal"
PAS_DIST_DIR="${DIST_DIR}/Pascal"

COMMON_PAS_TEMPLATE_DIR="${PAS_TEMPLATE_DIR}/Common"

FPC_PAS_TEMPLATE_DIR="${PAS_TEMPLATE_DIR}/FPC"
FPC_PAS_DIST_DIR="${PAS_DIST_DIR}/FPC"

# 
# Directories related to Source distribution
# 
SOURCE_DIST_DIR="${DIST_DIR}/Source"

