
  
  
 /* C Code  Auto-Generated by create_sdl_typeChecker.py*/
 
 
#include <stdio.h>
#ifdef __APPLE__
#include "SDL/SDL.h"
#else
#include "SDL.h"
#endif
void PascalCheckEnum_SDL_bool(int *ptr);
void PascalCheckEnum_SDL_DUMMY_ENUM(int *ptr);
void PascalCheckEnum_SDL_assert_state(int *ptr);
void PascalCheckEnum_SDL_errorcode(int *ptr);
void PascalCheckEnum_SDL_ThreadPriority(int *ptr);
void PascalCheckEnum_SDL_AudioStatus(int *ptr);
void PascalCheckEnum_SDL_BlendMode(int *ptr);
void PascalCheckEnum_SDL_WindowFlags(int *ptr);
void PascalCheckEnum_SDL_WindowEventID(int *ptr);
void PascalCheckEnum_SDL_GLattr(int *ptr);
void PascalCheckEnum_SDL_Scancode(int *ptr);
void PascalCheckEnum_SDL_Keymod(int *ptr);
void PascalCheckEnum_SDL_EventType(int *ptr);
void PascalCheckEnum_SDL_eventaction(int *ptr);
void PascalCheckEnum_SDL_HintPriority(int *ptr);
void PascalCheckEnum_SDL_LogPriority(int *ptr);
void PascalCheckEnum_SDL_PowerState(int *ptr);
void PascalCheckEnum_SDL_RendererFlags(int *ptr);
void PascalCheckEnum_SDL_TextureAccess(int *ptr);
void PascalCheckEnum_SDL_TextureModulate(int *ptr);
void PascalCheckEnum_SDL_GrabMode(int *ptr);
void PascalCheckRecord_SDL_assert_data(int *ptr);
void PascalCheckRecord_SDL_atomic_t(int *ptr);
void PascalCheckRecord_SDL_RWops(int *ptr);
void PascalCheckRecord_SDL_AudioSpec(int *ptr);
void PascalCheckRecord_SDL_AudioCVT(int *ptr);
void PascalCheckRecord_SDL_Color(int *ptr);
void PascalCheckRecord_SDL_Palette(int *ptr);
void PascalCheckRecord_SDL_PixelFormat(int *ptr);
void PascalCheckRecord_SDL_Point(int *ptr);
void PascalCheckRecord_SDL_Rect(int *ptr);
void PascalCheckRecord_SDL_Surface(int *ptr);
void PascalCheckRecord_SDL_DisplayMode(int *ptr);
void PascalCheckRecord_SDL_Keysym(int *ptr);
void PascalCheckRecord_SDL_Finger(int *ptr);
void PascalCheckRecord_SDL_Touch(int *ptr);
void PascalCheckRecord_SDL_WindowEvent(int *ptr);
void PascalCheckRecord_SDL_KeyboardEvent(int *ptr);
void PascalCheckRecord_SDL_TextEditingEvent(int *ptr);
void PascalCheckRecord_SDL_TextInputEvent(int *ptr);
void PascalCheckRecord_SDL_MouseMotionEvent(int *ptr);
void PascalCheckRecord_SDL_MouseButtonEvent(int *ptr);
void PascalCheckRecord_SDL_MouseWheelEvent(int *ptr);
void PascalCheckRecord_SDL_JoyAxisEvent(int *ptr);
void PascalCheckRecord_SDL_JoyBallEvent(int *ptr);
void PascalCheckRecord_SDL_JoyHatEvent(int *ptr);
void PascalCheckRecord_SDL_JoyButtonEvent(int *ptr);
void PascalCheckRecord_SDL_TouchFingerEvent(int *ptr);
void PascalCheckRecord_SDL_TouchButtonEvent(int *ptr);
void PascalCheckRecord_SDL_MultiGestureEvent(int *ptr);
void PascalCheckRecord_SDL_DollarGestureEvent(int *ptr);
void PascalCheckRecord_SDL_DropEvent(int *ptr);
void PascalCheckRecord_SDL_QuitEvent(int *ptr);
void PascalCheckRecord_SDL_UserEvent(int *ptr);
void PascalCheckRecord_SDL_SysWMEvent(int *ptr);
void PascalCheckRecord_SDL_ActiveEvent(int *ptr);
void PascalCheckRecord_SDL_ResizeEvent(int *ptr);
void PascalCheckRecord_SDL_Event(int *ptr);
void PascalCheckRecord_SDL_RendererInfo(int *ptr);
void PascalCheckRecord_SDL_version(int *ptr);
void PascalCheckRecord_SDL_VideoInfo(int *ptr);
void PascalCheckRecord_SDL_Overlay(int *ptr);

void c_check_enum_SDL_bool()
{
   int data[3];
   
   data[0] = sizeof(SDL_bool);
   data[1] = SDL_FALSE;
   data[2] = SDL_TRUE;

   printf("Checking SDL_bool...\n");
   PascalCheckEnum_SDL_bool(data);
   printf("    Done... SDL_bool\n");
}
void c_check_enum_SDL_DUMMY_ENUM()
{
   int data[2];
   
   data[0] = sizeof(SDL_DUMMY_ENUM);
   data[1] = DUMMY_ENUM_VALUE;

   printf("Checking SDL_DUMMY_ENUM...\n");
   PascalCheckEnum_SDL_DUMMY_ENUM(data);
   printf("    Done... SDL_DUMMY_ENUM\n");
}
void c_check_enum_SDL_assert_state()
{
   int data[6];
   
   data[0] = sizeof(SDL_assert_state);
   data[1] = SDL_ASSERTION_RETRY;
   data[2] = SDL_ASSERTION_BREAK;
   data[3] = SDL_ASSERTION_ABORT;
   data[4] = SDL_ASSERTION_IGNORE;
   data[5] = SDL_ASSERTION_ALWAYS_IGNORE;

   printf("Checking SDL_assert_state...\n");
   PascalCheckEnum_SDL_assert_state(data);
   printf("    Done... SDL_assert_state\n");
}
void c_check_enum_SDL_errorcode()
{
   int data[7];
   
   data[0] = sizeof(SDL_errorcode);
   data[1] = SDL_ENOMEM;
   data[2] = SDL_EFREAD;
   data[3] = SDL_EFWRITE;
   data[4] = SDL_EFSEEK;
   data[5] = SDL_UNSUPPORTED;
   data[6] = SDL_LASTERROR;

   printf("Checking SDL_errorcode...\n");
   PascalCheckEnum_SDL_errorcode(data);
   printf("    Done... SDL_errorcode\n");
}
void c_check_enum_SDL_ThreadPriority()
{
   int data[4];
   
   data[0] = sizeof(SDL_ThreadPriority);
   data[1] = SDL_THREAD_PRIORITY_LOW;
   data[2] = SDL_THREAD_PRIORITY_NORMAL;
   data[3] = SDL_THREAD_PRIORITY_HIGH;

   printf("Checking SDL_ThreadPriority...\n");
   PascalCheckEnum_SDL_ThreadPriority(data);
   printf("    Done... SDL_ThreadPriority\n");
}
void c_check_enum_SDL_AudioStatus()
{
   int data[4];
   
   data[0] = sizeof(SDL_AudioStatus);
   data[1] = SDL_AUDIO_STOPPED;
   data[2] = SDL_AUDIO_PLAYING;
   data[3] = SDL_AUDIO_PAUSED;

   printf("Checking SDL_AudioStatus...\n");
   PascalCheckEnum_SDL_AudioStatus(data);
   printf("    Done... SDL_AudioStatus\n");
}
void c_check_enum_SDL_BlendMode()
{
   int data[5];
   
   data[0] = sizeof(SDL_BlendMode);
   data[1] = SDL_BLENDMODE_NONE;
   data[2] = SDL_BLENDMODE_BLEND;
   data[3] = SDL_BLENDMODE_ADD;
   data[4] = SDL_BLENDMODE_MOD;

   printf("Checking SDL_BlendMode...\n");
   PascalCheckEnum_SDL_BlendMode(data);
   printf("    Done... SDL_BlendMode\n");
}
void c_check_enum_SDL_WindowFlags()
{
   int data[13];
   
   data[0] = sizeof(SDL_WindowFlags);
   data[1] = SDL_WINDOW_FULLSCREEN;
   data[2] = SDL_WINDOW_OPENGL;
   data[3] = SDL_WINDOW_SHOWN;
   data[4] = SDL_WINDOW_HIDDEN;
   data[5] = SDL_WINDOW_BORDERLESS;
   data[6] = SDL_WINDOW_RESIZABLE;
   data[7] = SDL_WINDOW_MINIMIZED;
   data[8] = SDL_WINDOW_MAXIMIZED;
   data[9] = SDL_WINDOW_INPUT_GRABBED;
   data[10] = SDL_WINDOW_INPUT_FOCUS;
   data[11] = SDL_WINDOW_MOUSE_FOCUS;
   data[12] = SDL_WINDOW_FOREIGN;

   printf("Checking SDL_WindowFlags...\n");
   PascalCheckEnum_SDL_WindowFlags(data);
   printf("    Done... SDL_WindowFlags\n");
}
void c_check_enum_SDL_WindowEventID()
{
   int data[16];
   
   data[0] = sizeof(SDL_WindowEventID);
   data[1] = SDL_WINDOWEVENT_NONE;
   data[2] = SDL_WINDOWEVENT_SHOWN;
   data[3] = SDL_WINDOWEVENT_HIDDEN;
   data[4] = SDL_WINDOWEVENT_EXPOSED;
   data[5] = SDL_WINDOWEVENT_MOVED;
   data[6] = SDL_WINDOWEVENT_RESIZED;
   data[7] = SDL_WINDOWEVENT_SIZE_CHANGED;
   data[8] = SDL_WINDOWEVENT_MINIMIZED;
   data[9] = SDL_WINDOWEVENT_MAXIMIZED;
   data[10] = SDL_WINDOWEVENT_RESTORED;
   data[11] = SDL_WINDOWEVENT_ENTER;
   data[12] = SDL_WINDOWEVENT_LEAVE;
   data[13] = SDL_WINDOWEVENT_FOCUS_GAINED;
   data[14] = SDL_WINDOWEVENT_FOCUS_LOST;
   data[15] = SDL_WINDOWEVENT_CLOSE;

   printf("Checking SDL_WindowEventID...\n");
   PascalCheckEnum_SDL_WindowEventID(data);
   printf("    Done... SDL_WindowEventID\n");
}
void c_check_enum_SDL_GLattr()
{
   int data[20];
   
   data[0] = sizeof(SDL_GLattr);
   data[1] = SDL_GL_RED_SIZE;
   data[2] = SDL_GL_GREEN_SIZE;
   data[3] = SDL_GL_BLUE_SIZE;
   data[4] = SDL_GL_ALPHA_SIZE;
   data[5] = SDL_GL_BUFFER_SIZE;
   data[6] = SDL_GL_DOUBLEBUFFER;
   data[7] = SDL_GL_DEPTH_SIZE;
   data[8] = SDL_GL_STENCIL_SIZE;
   data[9] = SDL_GL_ACCUM_RED_SIZE;
   data[10] = SDL_GL_ACCUM_GREEN_SIZE;
   data[11] = SDL_GL_ACCUM_BLUE_SIZE;
   data[12] = SDL_GL_ACCUM_ALPHA_SIZE;
   data[13] = SDL_GL_STEREO;
   data[14] = SDL_GL_MULTISAMPLEBUFFERS;
   data[15] = SDL_GL_MULTISAMPLESAMPLES;
   data[16] = SDL_GL_ACCELERATED_VISUAL;
   data[17] = SDL_GL_RETAINED_BACKING;
   data[18] = SDL_GL_CONTEXT_MAJOR_VERSION;
   data[19] = SDL_GL_CONTEXT_MINOR_VERSION;

   printf("Checking SDL_GLattr...\n");
   PascalCheckEnum_SDL_GLattr(data);
   printf("    Done... SDL_GLattr\n");
}
void c_check_enum_SDL_Scancode()
{
   int data[241];
   
   data[0] = sizeof(SDL_Scancode);
   data[1] = SDL_SCANCODE_UNKNOWN;
   data[2] = SDL_SCANCODE_A;
   data[3] = SDL_SCANCODE_B;
   data[4] = SDL_SCANCODE_C;
   data[5] = SDL_SCANCODE_D;
   data[6] = SDL_SCANCODE_E;
   data[7] = SDL_SCANCODE_F;
   data[8] = SDL_SCANCODE_G;
   data[9] = SDL_SCANCODE_H;
   data[10] = SDL_SCANCODE_I;
   data[11] = SDL_SCANCODE_J;
   data[12] = SDL_SCANCODE_K;
   data[13] = SDL_SCANCODE_L;
   data[14] = SDL_SCANCODE_M;
   data[15] = SDL_SCANCODE_N;
   data[16] = SDL_SCANCODE_O;
   data[17] = SDL_SCANCODE_P;
   data[18] = SDL_SCANCODE_Q;
   data[19] = SDL_SCANCODE_R;
   data[20] = SDL_SCANCODE_S;
   data[21] = SDL_SCANCODE_T;
   data[22] = SDL_SCANCODE_U;
   data[23] = SDL_SCANCODE_V;
   data[24] = SDL_SCANCODE_W;
   data[25] = SDL_SCANCODE_X;
   data[26] = SDL_SCANCODE_Y;
   data[27] = SDL_SCANCODE_Z;
   data[28] = SDL_SCANCODE_1;
   data[29] = SDL_SCANCODE_2;
   data[30] = SDL_SCANCODE_3;
   data[31] = SDL_SCANCODE_4;
   data[32] = SDL_SCANCODE_5;
   data[33] = SDL_SCANCODE_6;
   data[34] = SDL_SCANCODE_7;
   data[35] = SDL_SCANCODE_8;
   data[36] = SDL_SCANCODE_9;
   data[37] = SDL_SCANCODE_0;
   data[38] = SDL_SCANCODE_RETURN;
   data[39] = SDL_SCANCODE_ESCAPE;
   data[40] = SDL_SCANCODE_BACKSPACE;
   data[41] = SDL_SCANCODE_TAB;
   data[42] = SDL_SCANCODE_SPACE;
   data[43] = SDL_SCANCODE_MINUS;
   data[44] = SDL_SCANCODE_EQUALS;
   data[45] = SDL_SCANCODE_LEFTBRACKET;
   data[46] = SDL_SCANCODE_RIGHTBRACKET;
   data[47] = SDL_SCANCODE_BACKSLASH;
   data[48] = SDL_SCANCODE_NONUSHASH;
   data[49] = SDL_SCANCODE_SEMICOLON;
   data[50] = SDL_SCANCODE_APOSTROPHE;
   data[51] = SDL_SCANCODE_GRAVE;
   data[52] = SDL_SCANCODE_COMMA;
   data[53] = SDL_SCANCODE_PERIOD;
   data[54] = SDL_SCANCODE_SLASH;
   data[55] = SDL_SCANCODE_CAPSLOCK;
   data[56] = SDL_SCANCODE_F1;
   data[57] = SDL_SCANCODE_F2;
   data[58] = SDL_SCANCODE_F3;
   data[59] = SDL_SCANCODE_F4;
   data[60] = SDL_SCANCODE_F5;
   data[61] = SDL_SCANCODE_F6;
   data[62] = SDL_SCANCODE_F7;
   data[63] = SDL_SCANCODE_F8;
   data[64] = SDL_SCANCODE_F9;
   data[65] = SDL_SCANCODE_F10;
   data[66] = SDL_SCANCODE_F11;
   data[67] = SDL_SCANCODE_F12;
   data[68] = SDL_SCANCODE_PRINTSCREEN;
   data[69] = SDL_SCANCODE_SCROLLLOCK;
   data[70] = SDL_SCANCODE_PAUSE;
   data[71] = SDL_SCANCODE_INSERT;
   data[72] = SDL_SCANCODE_HOME;
   data[73] = SDL_SCANCODE_PAGEUP;
   data[74] = SDL_SCANCODE_DELETE;
   data[75] = SDL_SCANCODE_END;
   data[76] = SDL_SCANCODE_PAGEDOWN;
   data[77] = SDL_SCANCODE_RIGHT;
   data[78] = SDL_SCANCODE_LEFT;
   data[79] = SDL_SCANCODE_DOWN;
   data[80] = SDL_SCANCODE_UP;
   data[81] = SDL_SCANCODE_NUMLOCKCLEAR;
   data[82] = SDL_SCANCODE_KP_DIVIDE;
   data[83] = SDL_SCANCODE_KP_MULTIPLY;
   data[84] = SDL_SCANCODE_KP_MINUS;
   data[85] = SDL_SCANCODE_KP_PLUS;
   data[86] = SDL_SCANCODE_KP_ENTER;
   data[87] = SDL_SCANCODE_KP_1;
   data[88] = SDL_SCANCODE_KP_2;
   data[89] = SDL_SCANCODE_KP_3;
   data[90] = SDL_SCANCODE_KP_4;
   data[91] = SDL_SCANCODE_KP_5;
   data[92] = SDL_SCANCODE_KP_6;
   data[93] = SDL_SCANCODE_KP_7;
   data[94] = SDL_SCANCODE_KP_8;
   data[95] = SDL_SCANCODE_KP_9;
   data[96] = SDL_SCANCODE_KP_0;
   data[97] = SDL_SCANCODE_KP_PERIOD;
   data[98] = SDL_SCANCODE_NONUSBACKSLASH;
   data[99] = SDL_SCANCODE_APPLICATION;
   data[100] = SDL_SCANCODE_POWER;
   data[101] = SDL_SCANCODE_KP_EQUALS;
   data[102] = SDL_SCANCODE_F13;
   data[103] = SDL_SCANCODE_F14;
   data[104] = SDL_SCANCODE_F15;
   data[105] = SDL_SCANCODE_F16;
   data[106] = SDL_SCANCODE_F17;
   data[107] = SDL_SCANCODE_F18;
   data[108] = SDL_SCANCODE_F19;
   data[109] = SDL_SCANCODE_F20;
   data[110] = SDL_SCANCODE_F21;
   data[111] = SDL_SCANCODE_F22;
   data[112] = SDL_SCANCODE_F23;
   data[113] = SDL_SCANCODE_F24;
   data[114] = SDL_SCANCODE_EXECUTE;
   data[115] = SDL_SCANCODE_HELP;
   data[116] = SDL_SCANCODE_MENU;
   data[117] = SDL_SCANCODE_SELECT;
   data[118] = SDL_SCANCODE_STOP;
   data[119] = SDL_SCANCODE_AGAIN;
   data[120] = SDL_SCANCODE_UNDO;
   data[121] = SDL_SCANCODE_CUT;
   data[122] = SDL_SCANCODE_COPY;
   data[123] = SDL_SCANCODE_PASTE;
   data[124] = SDL_SCANCODE_FIND;
   data[125] = SDL_SCANCODE_MUTE;
   data[126] = SDL_SCANCODE_VOLUMEUP;
   data[127] = SDL_SCANCODE_VOLUMEDOWN;
   data[128] = SDL_SCANCODE_KP_COMMA;
   data[129] = SDL_SCANCODE_KP_EQUALSAS400;
   data[130] = SDL_SCANCODE_INTERNATIONAL1;
   data[131] = SDL_SCANCODE_INTERNATIONAL2;
   data[132] = SDL_SCANCODE_INTERNATIONAL3;
   data[133] = SDL_SCANCODE_INTERNATIONAL4;
   data[134] = SDL_SCANCODE_INTERNATIONAL5;
   data[135] = SDL_SCANCODE_INTERNATIONAL6;
   data[136] = SDL_SCANCODE_INTERNATIONAL7;
   data[137] = SDL_SCANCODE_INTERNATIONAL8;
   data[138] = SDL_SCANCODE_INTERNATIONAL9;
   data[139] = SDL_SCANCODE_LANG1;
   data[140] = SDL_SCANCODE_LANG2;
   data[141] = SDL_SCANCODE_LANG3;
   data[142] = SDL_SCANCODE_LANG4;
   data[143] = SDL_SCANCODE_LANG5;
   data[144] = SDL_SCANCODE_LANG6;
   data[145] = SDL_SCANCODE_LANG7;
   data[146] = SDL_SCANCODE_LANG8;
   data[147] = SDL_SCANCODE_LANG9;
   data[148] = SDL_SCANCODE_ALTERASE;
   data[149] = SDL_SCANCODE_SYSREQ;
   data[150] = SDL_SCANCODE_CANCEL;
   data[151] = SDL_SCANCODE_CLEAR;
   data[152] = SDL_SCANCODE_PRIOR;
   data[153] = SDL_SCANCODE_RETURN2;
   data[154] = SDL_SCANCODE_SEPARATOR;
   data[155] = SDL_SCANCODE_OUT;
   data[156] = SDL_SCANCODE_OPER;
   data[157] = SDL_SCANCODE_CLEARAGAIN;
   data[158] = SDL_SCANCODE_CRSEL;
   data[159] = SDL_SCANCODE_EXSEL;
   data[160] = SDL_SCANCODE_KP_00;
   data[161] = SDL_SCANCODE_KP_000;
   data[162] = SDL_SCANCODE_THOUSANDSSEPARATOR;
   data[163] = SDL_SCANCODE_DECIMALSEPARATOR;
   data[164] = SDL_SCANCODE_CURRENCYUNIT;
   data[165] = SDL_SCANCODE_CURRENCYSUBUNIT;
   data[166] = SDL_SCANCODE_KP_LEFTPAREN;
   data[167] = SDL_SCANCODE_KP_RIGHTPAREN;
   data[168] = SDL_SCANCODE_KP_LEFTBRACE;
   data[169] = SDL_SCANCODE_KP_RIGHTBRACE;
   data[170] = SDL_SCANCODE_KP_TAB;
   data[171] = SDL_SCANCODE_KP_BACKSPACE;
   data[172] = SDL_SCANCODE_KP_A;
   data[173] = SDL_SCANCODE_KP_B;
   data[174] = SDL_SCANCODE_KP_C;
   data[175] = SDL_SCANCODE_KP_D;
   data[176] = SDL_SCANCODE_KP_E;
   data[177] = SDL_SCANCODE_KP_F;
   data[178] = SDL_SCANCODE_KP_XOR;
   data[179] = SDL_SCANCODE_KP_POWER;
   data[180] = SDL_SCANCODE_KP_PERCENT;
   data[181] = SDL_SCANCODE_KP_LESS;
   data[182] = SDL_SCANCODE_KP_GREATER;
   data[183] = SDL_SCANCODE_KP_AMPERSAND;
   data[184] = SDL_SCANCODE_KP_DBLAMPERSAND;
   data[185] = SDL_SCANCODE_KP_VERTICALBAR;
   data[186] = SDL_SCANCODE_KP_DBLVERTICALBAR;
   data[187] = SDL_SCANCODE_KP_COLON;
   data[188] = SDL_SCANCODE_KP_HASH;
   data[189] = SDL_SCANCODE_KP_SPACE;
   data[190] = SDL_SCANCODE_KP_AT;
   data[191] = SDL_SCANCODE_KP_EXCLAM;
   data[192] = SDL_SCANCODE_KP_MEMSTORE;
   data[193] = SDL_SCANCODE_KP_MEMRECALL;
   data[194] = SDL_SCANCODE_KP_MEMCLEAR;
   data[195] = SDL_SCANCODE_KP_MEMADD;
   data[196] = SDL_SCANCODE_KP_MEMSUBTRACT;
   data[197] = SDL_SCANCODE_KP_MEMMULTIPLY;
   data[198] = SDL_SCANCODE_KP_MEMDIVIDE;
   data[199] = SDL_SCANCODE_KP_PLUSMINUS;
   data[200] = SDL_SCANCODE_KP_CLEAR;
   data[201] = SDL_SCANCODE_KP_CLEARENTRY;
   data[202] = SDL_SCANCODE_KP_BINARY;
   data[203] = SDL_SCANCODE_KP_OCTAL;
   data[204] = SDL_SCANCODE_KP_DECIMAL;
   data[205] = SDL_SCANCODE_KP_HEXADECIMAL;
   data[206] = SDL_SCANCODE_LCTRL;
   data[207] = SDL_SCANCODE_LSHIFT;
   data[208] = SDL_SCANCODE_LALT;
   data[209] = SDL_SCANCODE_LGUI;
   data[210] = SDL_SCANCODE_RCTRL;
   data[211] = SDL_SCANCODE_RSHIFT;
   data[212] = SDL_SCANCODE_RALT;
   data[213] = SDL_SCANCODE_RGUI;
   data[214] = SDL_SCANCODE_MODE;
   data[215] = SDL_SCANCODE_AUDIONEXT;
   data[216] = SDL_SCANCODE_AUDIOPREV;
   data[217] = SDL_SCANCODE_AUDIOSTOP;
   data[218] = SDL_SCANCODE_AUDIOPLAY;
   data[219] = SDL_SCANCODE_AUDIOMUTE;
   data[220] = SDL_SCANCODE_MEDIASELECT;
   data[221] = SDL_SCANCODE_WWW;
   data[222] = SDL_SCANCODE_MAIL;
   data[223] = SDL_SCANCODE_CALCULATOR;
   data[224] = SDL_SCANCODE_COMPUTER;
   data[225] = SDL_SCANCODE_AC_SEARCH;
   data[226] = SDL_SCANCODE_AC_HOME;
   data[227] = SDL_SCANCODE_AC_BACK;
   data[228] = SDL_SCANCODE_AC_FORWARD;
   data[229] = SDL_SCANCODE_AC_STOP;
   data[230] = SDL_SCANCODE_AC_REFRESH;
   data[231] = SDL_SCANCODE_AC_BOOKMARKS;
   data[232] = SDL_SCANCODE_BRIGHTNESSDOWN;
   data[233] = SDL_SCANCODE_BRIGHTNESSUP;
   data[234] = SDL_SCANCODE_DISPLAYSWITCH;
   data[235] = SDL_SCANCODE_KBDILLUMTOGGLE;
   data[236] = SDL_SCANCODE_KBDILLUMDOWN;
   data[237] = SDL_SCANCODE_KBDILLUMUP;
   data[238] = SDL_SCANCODE_EJECT;
   data[239] = SDL_SCANCODE_SLEEP;
   data[240] = SDL_NUM_SCANCODES;

   printf("Checking SDL_Scancode...\n");
   PascalCheckEnum_SDL_Scancode(data);
   printf("    Done... SDL_Scancode\n");
}
void c_check_enum_SDL_Keymod()
{
   int data[14];
   
   data[0] = sizeof(SDL_Keymod);
   data[1] = KMOD_NONE;
   data[2] = KMOD_LSHIFT;
   data[3] = KMOD_RSHIFT;
   data[4] = KMOD_LCTRL;
   data[5] = KMOD_RCTRL;
   data[6] = KMOD_LALT;
   data[7] = KMOD_RALT;
   data[8] = KMOD_LGUI;
   data[9] = KMOD_RGUI;
   data[10] = KMOD_NUM;
   data[11] = KMOD_CAPS;
   data[12] = KMOD_MODE;
   data[13] = KMOD_RESERVED;

   printf("Checking SDL_Keymod...\n");
   PascalCheckEnum_SDL_Keymod(data);
   printf("    Done... SDL_Keymod\n");
}
void c_check_enum_SDL_EventType()
{
   int data[39];
   
   data[0] = sizeof(SDL_EventType);
   data[1] = SDL_FIRSTEVENT;
   data[2] = SDL_QUIT;
   data[3] = SDL_WINDOWEVENT;
   data[4] = SDL_SYSWMEVENT;
   data[5] = SDL_KEYDOWN;
   data[6] = SDL_KEYUP;
   data[7] = SDL_TEXTEDITING;
   data[8] = SDL_TEXTINPUT;
   data[9] = SDL_MOUSEMOTION;
   data[10] = SDL_MOUSEBUTTONDOWN;
   data[11] = SDL_MOUSEBUTTONUP;
   data[12] = SDL_MOUSEWHEEL;
   data[13] = SDL_INPUTMOTION;
   data[14] = SDL_INPUTBUTTONDOWN;
   data[15] = SDL_INPUTBUTTONUP;
   data[16] = SDL_INPUTWHEEL;
   data[17] = SDL_INPUTPROXIMITYIN;
   data[18] = SDL_INPUTPROXIMITYOUT;
   data[19] = SDL_JOYAXISMOTION;
   data[20] = SDL_JOYBALLMOTION;
   data[21] = SDL_JOYHATMOTION;
   data[22] = SDL_JOYBUTTONDOWN;
   data[23] = SDL_JOYBUTTONUP;
   data[24] = SDL_FINGERDOWN;
   data[25] = SDL_FINGERUP;
   data[26] = SDL_FINGERMOTION;
   data[27] = SDL_TOUCHBUTTONDOWN;
   data[28] = SDL_TOUCHBUTTONUP;
   data[29] = SDL_DOLLARGESTURE;
   data[30] = SDL_DOLLARRECORD;
   data[31] = SDL_MULTIGESTURE;
   data[32] = SDL_CLIPBOARDUPDATE;
   data[33] = SDL_DROPFILE;
   data[34] = SDL_EVENT_COMPAT1;
   data[35] = SDL_EVENT_COMPAT2;
   data[36] = SDL_EVENT_COMPAT3;
   data[37] = SDL_USEREVENT;
   data[38] = SDL_LASTEVENT;

   printf("Checking SDL_EventType...\n");
   PascalCheckEnum_SDL_EventType(data);
   printf("    Done... SDL_EventType\n");
}
void c_check_enum_SDL_eventaction()
{
   int data[4];
   
   data[0] = sizeof(SDL_eventaction);
   data[1] = SDL_ADDEVENT;
   data[2] = SDL_PEEKEVENT;
   data[3] = SDL_GETEVENT;

   printf("Checking SDL_eventaction...\n");
   PascalCheckEnum_SDL_eventaction(data);
   printf("    Done... SDL_eventaction\n");
}
void c_check_enum_SDL_HintPriority()
{
   int data[4];
   
   data[0] = sizeof(SDL_HintPriority);
   data[1] = SDL_HINT_DEFAULT;
   data[2] = SDL_HINT_NORMAL;
   data[3] = SDL_HINT_OVERRIDE;

   printf("Checking SDL_HintPriority...\n");
   PascalCheckEnum_SDL_HintPriority(data);
   printf("    Done... SDL_HintPriority\n");
}
void c_check_enum_SDL_LogPriority()
{
   int data[8];
   
   data[0] = sizeof(SDL_LogPriority);
   data[1] = SDL_LOG_PRIORITY_VERBOSE;
   data[2] = SDL_LOG_PRIORITY_DEBUG;
   data[3] = SDL_LOG_PRIORITY_INFO;
   data[4] = SDL_LOG_PRIORITY_WARN;
   data[5] = SDL_LOG_PRIORITY_ERROR;
   data[6] = SDL_LOG_PRIORITY_CRITICAL;
   data[7] = SDL_NUM_LOG_PRIORITIES;

   printf("Checking SDL_LogPriority...\n");
   PascalCheckEnum_SDL_LogPriority(data);
   printf("    Done... SDL_LogPriority\n");
}
void c_check_enum_SDL_PowerState()
{
   int data[6];
   
   data[0] = sizeof(SDL_PowerState);
   data[1] = SDL_POWERSTATE_UNKNOWN;
   data[2] = SDL_POWERSTATE_ON_BATTERY;
   data[3] = SDL_POWERSTATE_NO_BATTERY;
   data[4] = SDL_POWERSTATE_CHARGING;
   data[5] = SDL_POWERSTATE_CHARGED;

   printf("Checking SDL_PowerState...\n");
   PascalCheckEnum_SDL_PowerState(data);
   printf("    Done... SDL_PowerState\n");
}
void c_check_enum_SDL_RendererFlags()
{
   int data[4];
   
   data[0] = sizeof(SDL_RendererFlags);
   data[1] = SDL_RENDERER_SOFTWARE;
   data[2] = SDL_RENDERER_ACCELERATED;
   data[3] = SDL_RENDERER_PRESENTVSYNC;

   printf("Checking SDL_RendererFlags...\n");
   PascalCheckEnum_SDL_RendererFlags(data);
   printf("    Done... SDL_RendererFlags\n");
}
void c_check_enum_SDL_TextureAccess()
{
   int data[3];
   
   data[0] = sizeof(SDL_TextureAccess);
   data[1] = SDL_TEXTUREACCESS_STATIC;
   data[2] = SDL_TEXTUREACCESS_STREAMING;

   printf("Checking SDL_TextureAccess...\n");
   PascalCheckEnum_SDL_TextureAccess(data);
   printf("    Done... SDL_TextureAccess\n");
}
void c_check_enum_SDL_TextureModulate()
{
   int data[4];
   
   data[0] = sizeof(SDL_TextureModulate);
   data[1] = SDL_TEXTUREMODULATE_NONE;
   data[2] = SDL_TEXTUREMODULATE_COLOR;
   data[3] = SDL_TEXTUREMODULATE_ALPHA;

   printf("Checking SDL_TextureModulate...\n");
   PascalCheckEnum_SDL_TextureModulate(data);
   printf("    Done... SDL_TextureModulate\n");
}
void c_check_enum_SDL_GrabMode()
{
   int data[4];
   
   data[0] = sizeof(SDL_GrabMode);
   data[1] = SDL_GRAB_QUERY;
   data[2] = SDL_GRAB_OFF;
   data[3] = SDL_GRAB_ON;

   printf("Checking SDL_GrabMode...\n");
   PascalCheckEnum_SDL_GrabMode(data);
   printf("    Done... SDL_GrabMode\n");
}
    void c_check_Record_SDL_assert_data() 
    {
        SDL_assert_data _SDL_assert_data;
        int data[8];
        void *start = &_SDL_assert_data;
        data[0] = sizeof(SDL_assert_data);
        
        printf("Checking SDL_assert_data...\n");
        data[1] = ((long)&_SDL_assert_data.always_ignore) - ((long)start);
        data[2] = ((long)&_SDL_assert_data.trigger_count) - ((long)start);
        data[3] = ((long)&_SDL_assert_data.condition) - ((long)start);
        data[4] = ((long)&_SDL_assert_data.filename) - ((long)start);
        data[5] = ((long)&_SDL_assert_data.linenum) - ((long)start);
        data[6] = ((long)&_SDL_assert_data.function) - ((long)start);
        data[7] = ((long)&_SDL_assert_data.next) - ((long)start);

        PascalCheckRecord_SDL_assert_data(data);
        printf("    Done... SDL_assert_data\n");
    }
    
    void c_check_Record_SDL_atomic_t() 
    {
        SDL_atomic_t _SDL_atomic_t;
        int data[2];
        void *start = &_SDL_atomic_t;
        data[0] = sizeof(SDL_atomic_t);
        
        printf("Checking SDL_atomic_t...\n");
        data[1] = ((long)&_SDL_atomic_t.value) - ((long)start);

        PascalCheckRecord_SDL_atomic_t(data);
        printf("    Done... SDL_atomic_t\n");
    }
    
    void c_check_Record_SDL_RWops() 
    {
        SDL_RWops _SDL_RWops;
        int data[16];
        void *start = &_SDL_RWops;
        data[0] = sizeof(SDL_RWops);
        
        printf("Checking SDL_RWops...\n");
        data[1] = ((long)&_SDL_RWops.seek) - ((long)start);
        data[2] = ((long)&_SDL_RWops.read) - ((long)start);
        data[3] = ((long)&_SDL_RWops.write) - ((long)start);
        data[4] = ((long)&_SDL_RWops.close) - ((long)start);
        data[5] = ((long)&_SDL_RWops.type) - ((long)start);
        data[6] = ((long)&_SDL_RWops.hidden) - ((long)start);
        data[7] = ((long)&_SDL_RWops.hidden.stdio) - ((long)start);
        data[8] = ((long)&_SDL_RWops.hidden.stdio.autoclose) - ((long)start);
        data[9] = ((long)&_SDL_RWops.hidden.stdio.fp) - ((long)start);
        data[10] = ((long)&_SDL_RWops.hidden.mem) - ((long)start);
        data[11] = ((long)&_SDL_RWops.hidden.mem.base) - ((long)start);
        data[12] = ((long)&_SDL_RWops.hidden.mem.here) - ((long)start);
        data[13] = ((long)&_SDL_RWops.hidden.mem.stop) - ((long)start);
        data[14] = ((long)&_SDL_RWops.hidden.unknown) - ((long)start);
        data[15] = ((long)&_SDL_RWops.hidden.unknown.data1) - ((long)start);

        PascalCheckRecord_SDL_RWops(data);
        printf("    Done... SDL_RWops\n");
    }
    
    void c_check_Record_SDL_AudioSpec() 
    {
        SDL_AudioSpec _SDL_AudioSpec;
        int data[10];
        void *start = &_SDL_AudioSpec;
        data[0] = sizeof(SDL_AudioSpec);
        
        printf("Checking SDL_AudioSpec...\n");
        data[1] = ((long)&_SDL_AudioSpec.freq) - ((long)start);
        data[2] = ((long)&_SDL_AudioSpec.format) - ((long)start);
        data[3] = ((long)&_SDL_AudioSpec.channels) - ((long)start);
        data[4] = ((long)&_SDL_AudioSpec.silence) - ((long)start);
        data[5] = ((long)&_SDL_AudioSpec.samples) - ((long)start);
        data[6] = ((long)&_SDL_AudioSpec.padding) - ((long)start);
        data[7] = ((long)&_SDL_AudioSpec.size) - ((long)start);
        data[8] = ((long)&_SDL_AudioSpec.callback) - ((long)start);
        data[9] = ((long)&_SDL_AudioSpec.userdata) - ((long)start);

        PascalCheckRecord_SDL_AudioSpec(data);
        printf("    Done... SDL_AudioSpec\n");
    }
    
    void c_check_Record_SDL_AudioCVT() 
    {
        SDL_AudioCVT _SDL_AudioCVT;
        int data[12];
        void *start = &_SDL_AudioCVT;
        data[0] = sizeof(SDL_AudioCVT);
        
        printf("Checking SDL_AudioCVT...\n");
        data[1] = ((long)&_SDL_AudioCVT.needed) - ((long)start);
        data[2] = ((long)&_SDL_AudioCVT.src_format) - ((long)start);
        data[3] = ((long)&_SDL_AudioCVT.dst_format) - ((long)start);
        data[4] = ((long)&_SDL_AudioCVT.rate_incr) - ((long)start);
        data[5] = ((long)&_SDL_AudioCVT.buf) - ((long)start);
        data[6] = ((long)&_SDL_AudioCVT.len) - ((long)start);
        data[7] = ((long)&_SDL_AudioCVT.len_cvt) - ((long)start);
        data[8] = ((long)&_SDL_AudioCVT.len_mult) - ((long)start);
        data[9] = ((long)&_SDL_AudioCVT.len_ratio) - ((long)start);
        data[10] = ((long)&_SDL_AudioCVT.filters) - ((long)start);
        data[11] = ((long)&_SDL_AudioCVT.filter_index) - ((long)start);

        PascalCheckRecord_SDL_AudioCVT(data);
        printf("    Done... SDL_AudioCVT\n");
    }
    
    void c_check_Record_SDL_Color() 
    {
        SDL_Color _SDL_Color;
        int data[5];
        void *start = &_SDL_Color;
        data[0] = sizeof(SDL_Color);
        
        printf("Checking SDL_Color...\n");
        data[1] = ((long)&_SDL_Color.r) - ((long)start);
        data[2] = ((long)&_SDL_Color.g) - ((long)start);
        data[3] = ((long)&_SDL_Color.b) - ((long)start);
        data[4] = ((long)&_SDL_Color.unused) - ((long)start);

        PascalCheckRecord_SDL_Color(data);
        printf("    Done... SDL_Color\n");
    }
    
    void c_check_Record_SDL_Palette() 
    {
        SDL_Palette _SDL_Palette;
        int data[5];
        void *start = &_SDL_Palette;
        data[0] = sizeof(SDL_Palette);
        
        printf("Checking SDL_Palette...\n");
        data[1] = ((long)&_SDL_Palette.ncolors) - ((long)start);
        data[2] = ((long)&_SDL_Palette.colors) - ((long)start);
        data[3] = ((long)&_SDL_Palette.version) - ((long)start);
        data[4] = ((long)&_SDL_Palette.refcount) - ((long)start);

        PascalCheckRecord_SDL_Palette(data);
        printf("    Done... SDL_Palette\n");
    }
    
    void c_check_Record_SDL_PixelFormat() 
    {
        SDL_PixelFormat _SDL_PixelFormat;
        int data[20];
        void *start = &_SDL_PixelFormat;
        data[0] = sizeof(SDL_PixelFormat);
        
        printf("Checking SDL_PixelFormat...\n");
        data[1] = ((long)&_SDL_PixelFormat.format) - ((long)start);
        data[2] = ((long)&_SDL_PixelFormat.palette) - ((long)start);
        data[3] = ((long)&_SDL_PixelFormat.BitsPerPixel) - ((long)start);
        data[4] = ((long)&_SDL_PixelFormat.BytesPerPixel) - ((long)start);
        data[5] = ((long)&_SDL_PixelFormat.padding) - ((long)start);
        data[6] = ((long)&_SDL_PixelFormat.Rmask) - ((long)start);
        data[7] = ((long)&_SDL_PixelFormat.Gmask) - ((long)start);
        data[8] = ((long)&_SDL_PixelFormat.Bmask) - ((long)start);
        data[9] = ((long)&_SDL_PixelFormat.Amask) - ((long)start);
        data[10] = ((long)&_SDL_PixelFormat.Rloss) - ((long)start);
        data[11] = ((long)&_SDL_PixelFormat.Gloss) - ((long)start);
        data[12] = ((long)&_SDL_PixelFormat.Bloss) - ((long)start);
        data[13] = ((long)&_SDL_PixelFormat.Aloss) - ((long)start);
        data[14] = ((long)&_SDL_PixelFormat.Rshift) - ((long)start);
        data[15] = ((long)&_SDL_PixelFormat.Gshift) - ((long)start);
        data[16] = ((long)&_SDL_PixelFormat.Bshift) - ((long)start);
        data[17] = ((long)&_SDL_PixelFormat.Ashift) - ((long)start);
        data[18] = ((long)&_SDL_PixelFormat.refcount) - ((long)start);
        data[19] = ((long)&_SDL_PixelFormat.next) - ((long)start);

        PascalCheckRecord_SDL_PixelFormat(data);
        printf("    Done... SDL_PixelFormat\n");
    }
    
    void c_check_Record_SDL_Point() 
    {
        SDL_Point _SDL_Point;
        int data[3];
        void *start = &_SDL_Point;
        data[0] = sizeof(SDL_Point);
        
        printf("Checking SDL_Point...\n");
        data[1] = ((long)&_SDL_Point.x) - ((long)start);
        data[2] = ((long)&_SDL_Point.y) - ((long)start);

        PascalCheckRecord_SDL_Point(data);
        printf("    Done... SDL_Point\n");
    }
    
    void c_check_Record_SDL_Rect() 
    {
        SDL_Rect _SDL_Rect;
        int data[5];
        void *start = &_SDL_Rect;
        data[0] = sizeof(SDL_Rect);
        
        printf("Checking SDL_Rect...\n");
        data[1] = ((long)&_SDL_Rect.x) - ((long)start);
        data[2] = ((long)&_SDL_Rect.y) - ((long)start);
        data[3] = ((long)&_SDL_Rect.w) - ((long)start);
        data[4] = ((long)&_SDL_Rect.h) - ((long)start);

        PascalCheckRecord_SDL_Rect(data);
        printf("    Done... SDL_Rect\n");
    }
    
    void c_check_Record_SDL_Surface() 
    {
        SDL_Surface _SDL_Surface;
        int data[13];
        void *start = &_SDL_Surface;
        data[0] = sizeof(SDL_Surface);
        
        printf("Checking SDL_Surface...\n");
        data[1] = ((long)&_SDL_Surface.flags) - ((long)start);
        data[2] = ((long)&_SDL_Surface.format) - ((long)start);
        data[3] = ((long)&_SDL_Surface.w) - ((long)start);
        data[4] = ((long)&_SDL_Surface.h) - ((long)start);
        data[5] = ((long)&_SDL_Surface.pitch) - ((long)start);
        data[6] = ((long)&_SDL_Surface.pixels) - ((long)start);
        data[7] = ((long)&_SDL_Surface.userdata) - ((long)start);
        data[8] = ((long)&_SDL_Surface.locked) - ((long)start);
        data[9] = ((long)&_SDL_Surface.lock_data) - ((long)start);
        data[10] = ((long)&_SDL_Surface.clip_rect) - ((long)start);
        data[11] = ((long)&_SDL_Surface.map) - ((long)start);
        data[12] = ((long)&_SDL_Surface.refcount) - ((long)start);

        PascalCheckRecord_SDL_Surface(data);
        printf("    Done... SDL_Surface\n");
    }
    
    void c_check_Record_SDL_DisplayMode() 
    {
        SDL_DisplayMode _SDL_DisplayMode;
        int data[6];
        void *start = &_SDL_DisplayMode;
        data[0] = sizeof(SDL_DisplayMode);
        
        printf("Checking SDL_DisplayMode...\n");
        data[1] = ((long)&_SDL_DisplayMode.format) - ((long)start);
        data[2] = ((long)&_SDL_DisplayMode.w) - ((long)start);
        data[3] = ((long)&_SDL_DisplayMode.h) - ((long)start);
        data[4] = ((long)&_SDL_DisplayMode.refresh_rate) - ((long)start);
        data[5] = ((long)&_SDL_DisplayMode.driverdata) - ((long)start);

        PascalCheckRecord_SDL_DisplayMode(data);
        printf("    Done... SDL_DisplayMode\n");
    }
    
    void c_check_Record_SDL_Keysym() 
    {
        SDL_Keysym _SDL_Keysym;
        int data[5];
        void *start = &_SDL_Keysym;
        data[0] = sizeof(SDL_Keysym);
        
        printf("Checking SDL_Keysym...\n");
        data[1] = ((long)&_SDL_Keysym.scancode) - ((long)start);
        data[2] = ((long)&_SDL_Keysym.sym) - ((long)start);
        data[3] = ((long)&_SDL_Keysym.mod) - ((long)start);
        data[4] = ((long)&_SDL_Keysym.unicode) - ((long)start);

        PascalCheckRecord_SDL_Keysym(data);
        printf("    Done... SDL_Keysym\n");
    }
    
    void c_check_Record_SDL_Finger() 
    {
        SDL_Finger _SDL_Finger;
        int data[11];
        void *start = &_SDL_Finger;
        data[0] = sizeof(SDL_Finger);
        
        printf("Checking SDL_Finger...\n");
        data[1] = ((long)&_SDL_Finger.id) - ((long)start);
        data[2] = ((long)&_SDL_Finger.x) - ((long)start);
        data[3] = ((long)&_SDL_Finger.y) - ((long)start);
        data[4] = ((long)&_SDL_Finger.pressure) - ((long)start);
        data[5] = ((long)&_SDL_Finger.xdelta) - ((long)start);
        data[6] = ((long)&_SDL_Finger.ydelta) - ((long)start);
        data[7] = ((long)&_SDL_Finger.last_x) - ((long)start);
        data[8] = ((long)&_SDL_Finger.last_y) - ((long)start);
        data[9] = ((long)&_SDL_Finger.last_pressure) - ((long)start);
        data[10] = ((long)&_SDL_Finger.down) - ((long)start);

        PascalCheckRecord_SDL_Finger(data);
        printf("    Done... SDL_Finger\n");
    }
    
    void c_check_Record_SDL_Touch() 
    {
        SDL_Touch _SDL_Touch;
        int data[26];
        void *start = &_SDL_Touch;
        data[0] = sizeof(SDL_Touch);
        
        printf("Checking SDL_Touch...\n");
        data[1] = ((long)&_SDL_Touch.FreeTouch) - ((long)start);
        data[2] = ((long)&_SDL_Touch.pressure_max) - ((long)start);
        data[3] = ((long)&_SDL_Touch.pressure_min) - ((long)start);
        data[4] = ((long)&_SDL_Touch.x_max) - ((long)start);
        data[5] = ((long)&_SDL_Touch.x_min) - ((long)start);
        data[6] = ((long)&_SDL_Touch.y_max) - ((long)start);
        data[7] = ((long)&_SDL_Touch.y_min) - ((long)start);
        data[8] = ((long)&_SDL_Touch.xres) - ((long)start);
        data[9] = ((long)&_SDL_Touch.yres) - ((long)start);
        data[10] = ((long)&_SDL_Touch.pressureres) - ((long)start);
        data[11] = ((long)&_SDL_Touch.native_xres) - ((long)start);
        data[12] = ((long)&_SDL_Touch.native_yres) - ((long)start);
        data[13] = ((long)&_SDL_Touch.native_pressureres) - ((long)start);
        data[14] = ((long)&_SDL_Touch.tilt) - ((long)start);
        data[15] = ((long)&_SDL_Touch.rotation) - ((long)start);
        data[16] = ((long)&_SDL_Touch.id) - ((long)start);
        data[17] = ((long)&_SDL_Touch.focus) - ((long)start);
        data[18] = ((long)&_SDL_Touch.name) - ((long)start);
        data[19] = ((long)&_SDL_Touch.buttonstate) - ((long)start);
        data[20] = ((long)&_SDL_Touch.relative_mode) - ((long)start);
        data[21] = ((long)&_SDL_Touch.flush_motion) - ((long)start);
        data[22] = ((long)&_SDL_Touch.num_fingers) - ((long)start);
        data[23] = ((long)&_SDL_Touch.max_fingers) - ((long)start);
        data[24] = ((long)&_SDL_Touch.fingers) - ((long)start);
        data[25] = ((long)&_SDL_Touch.driverdata) - ((long)start);

        PascalCheckRecord_SDL_Touch(data);
        printf("    Done... SDL_Touch\n");
    }
    
    void c_check_Record_SDL_WindowEvent() 
    {
        SDL_WindowEvent _SDL_WindowEvent;
        int data[10];
        void *start = &_SDL_WindowEvent;
        data[0] = sizeof(SDL_WindowEvent);
        
        printf("Checking SDL_WindowEvent...\n");
        data[1] = ((long)&_SDL_WindowEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_WindowEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_WindowEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_WindowEvent.event) - ((long)start);
        data[5] = ((long)&_SDL_WindowEvent.padding1) - ((long)start);
        data[6] = ((long)&_SDL_WindowEvent.padding2) - ((long)start);
        data[7] = ((long)&_SDL_WindowEvent.padding3) - ((long)start);
        data[8] = ((long)&_SDL_WindowEvent.data1) - ((long)start);
        data[9] = ((long)&_SDL_WindowEvent.data2) - ((long)start);

        PascalCheckRecord_SDL_WindowEvent(data);
        printf("    Done... SDL_WindowEvent\n");
    }
    
    void c_check_Record_SDL_KeyboardEvent() 
    {
        SDL_KeyboardEvent _SDL_KeyboardEvent;
        int data[9];
        void *start = &_SDL_KeyboardEvent;
        data[0] = sizeof(SDL_KeyboardEvent);
        
        printf("Checking SDL_KeyboardEvent...\n");
        data[1] = ((long)&_SDL_KeyboardEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_KeyboardEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_KeyboardEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_KeyboardEvent.state) - ((long)start);
        data[5] = ((long)&_SDL_KeyboardEvent.repeat) - ((long)start);
        data[6] = ((long)&_SDL_KeyboardEvent.padding2) - ((long)start);
        data[7] = ((long)&_SDL_KeyboardEvent.padding3) - ((long)start);
        data[8] = ((long)&_SDL_KeyboardEvent.keysym) - ((long)start);

        PascalCheckRecord_SDL_KeyboardEvent(data);
        printf("    Done... SDL_KeyboardEvent\n");
    }
    
    void c_check_Record_SDL_TextEditingEvent() 
    {
        SDL_TextEditingEvent _SDL_TextEditingEvent;
        int data[7];
        void *start = &_SDL_TextEditingEvent;
        data[0] = sizeof(SDL_TextEditingEvent);
        
        printf("Checking SDL_TextEditingEvent...\n");
        data[1] = ((long)&_SDL_TextEditingEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_TextEditingEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_TextEditingEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_TextEditingEvent.text) - ((long)start);
        data[5] = ((long)&_SDL_TextEditingEvent.start) - ((long)start);
        data[6] = ((long)&_SDL_TextEditingEvent.length) - ((long)start);

        PascalCheckRecord_SDL_TextEditingEvent(data);
        printf("    Done... SDL_TextEditingEvent\n");
    }
    
    void c_check_Record_SDL_TextInputEvent() 
    {
        SDL_TextInputEvent _SDL_TextInputEvent;
        int data[5];
        void *start = &_SDL_TextInputEvent;
        data[0] = sizeof(SDL_TextInputEvent);
        
        printf("Checking SDL_TextInputEvent...\n");
        data[1] = ((long)&_SDL_TextInputEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_TextInputEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_TextInputEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_TextInputEvent.text) - ((long)start);

        PascalCheckRecord_SDL_TextInputEvent(data);
        printf("    Done... SDL_TextInputEvent\n");
    }
    
    void c_check_Record_SDL_MouseMotionEvent() 
    {
        SDL_MouseMotionEvent _SDL_MouseMotionEvent;
        int data[12];
        void *start = &_SDL_MouseMotionEvent;
        data[0] = sizeof(SDL_MouseMotionEvent);
        
        printf("Checking SDL_MouseMotionEvent...\n");
        data[1] = ((long)&_SDL_MouseMotionEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_MouseMotionEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_MouseMotionEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_MouseMotionEvent.state) - ((long)start);
        data[5] = ((long)&_SDL_MouseMotionEvent.padding1) - ((long)start);
        data[6] = ((long)&_SDL_MouseMotionEvent.padding2) - ((long)start);
        data[7] = ((long)&_SDL_MouseMotionEvent.padding3) - ((long)start);
        data[8] = ((long)&_SDL_MouseMotionEvent.x) - ((long)start);
        data[9] = ((long)&_SDL_MouseMotionEvent.y) - ((long)start);
        data[10] = ((long)&_SDL_MouseMotionEvent.xrel) - ((long)start);
        data[11] = ((long)&_SDL_MouseMotionEvent.yrel) - ((long)start);

        PascalCheckRecord_SDL_MouseMotionEvent(data);
        printf("    Done... SDL_MouseMotionEvent\n");
    }
    
    void c_check_Record_SDL_MouseButtonEvent() 
    {
        SDL_MouseButtonEvent _SDL_MouseButtonEvent;
        int data[10];
        void *start = &_SDL_MouseButtonEvent;
        data[0] = sizeof(SDL_MouseButtonEvent);
        
        printf("Checking SDL_MouseButtonEvent...\n");
        data[1] = ((long)&_SDL_MouseButtonEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_MouseButtonEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_MouseButtonEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_MouseButtonEvent.button) - ((long)start);
        data[5] = ((long)&_SDL_MouseButtonEvent.state) - ((long)start);
        data[6] = ((long)&_SDL_MouseButtonEvent.padding1) - ((long)start);
        data[7] = ((long)&_SDL_MouseButtonEvent.padding2) - ((long)start);
        data[8] = ((long)&_SDL_MouseButtonEvent.x) - ((long)start);
        data[9] = ((long)&_SDL_MouseButtonEvent.y) - ((long)start);

        PascalCheckRecord_SDL_MouseButtonEvent(data);
        printf("    Done... SDL_MouseButtonEvent\n");
    }
    
    void c_check_Record_SDL_MouseWheelEvent() 
    {
        SDL_MouseWheelEvent _SDL_MouseWheelEvent;
        int data[6];
        void *start = &_SDL_MouseWheelEvent;
        data[0] = sizeof(SDL_MouseWheelEvent);
        
        printf("Checking SDL_MouseWheelEvent...\n");
        data[1] = ((long)&_SDL_MouseWheelEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_MouseWheelEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_MouseWheelEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_MouseWheelEvent.x) - ((long)start);
        data[5] = ((long)&_SDL_MouseWheelEvent.y) - ((long)start);

        PascalCheckRecord_SDL_MouseWheelEvent(data);
        printf("    Done... SDL_MouseWheelEvent\n");
    }
    
    void c_check_Record_SDL_JoyAxisEvent() 
    {
        SDL_JoyAxisEvent _SDL_JoyAxisEvent;
        int data[8];
        void *start = &_SDL_JoyAxisEvent;
        data[0] = sizeof(SDL_JoyAxisEvent);
        
        printf("Checking SDL_JoyAxisEvent...\n");
        data[1] = ((long)&_SDL_JoyAxisEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_JoyAxisEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_JoyAxisEvent.which) - ((long)start);
        data[4] = ((long)&_SDL_JoyAxisEvent.axis) - ((long)start);
        data[5] = ((long)&_SDL_JoyAxisEvent.padding1) - ((long)start);
        data[6] = ((long)&_SDL_JoyAxisEvent.padding2) - ((long)start);
        data[7] = ((long)&_SDL_JoyAxisEvent.value) - ((long)start);

        PascalCheckRecord_SDL_JoyAxisEvent(data);
        printf("    Done... SDL_JoyAxisEvent\n");
    }
    
    void c_check_Record_SDL_JoyBallEvent() 
    {
        SDL_JoyBallEvent _SDL_JoyBallEvent;
        int data[9];
        void *start = &_SDL_JoyBallEvent;
        data[0] = sizeof(SDL_JoyBallEvent);
        
        printf("Checking SDL_JoyBallEvent...\n");
        data[1] = ((long)&_SDL_JoyBallEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_JoyBallEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_JoyBallEvent.which) - ((long)start);
        data[4] = ((long)&_SDL_JoyBallEvent.ball) - ((long)start);
        data[5] = ((long)&_SDL_JoyBallEvent.padding1) - ((long)start);
        data[6] = ((long)&_SDL_JoyBallEvent.padding2) - ((long)start);
        data[7] = ((long)&_SDL_JoyBallEvent.xrel) - ((long)start);
        data[8] = ((long)&_SDL_JoyBallEvent.yrel) - ((long)start);

        PascalCheckRecord_SDL_JoyBallEvent(data);
        printf("    Done... SDL_JoyBallEvent\n");
    }
    
    void c_check_Record_SDL_JoyHatEvent() 
    {
        SDL_JoyHatEvent _SDL_JoyHatEvent;
        int data[7];
        void *start = &_SDL_JoyHatEvent;
        data[0] = sizeof(SDL_JoyHatEvent);
        
        printf("Checking SDL_JoyHatEvent...\n");
        data[1] = ((long)&_SDL_JoyHatEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_JoyHatEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_JoyHatEvent.which) - ((long)start);
        data[4] = ((long)&_SDL_JoyHatEvent.hat) - ((long)start);
        data[5] = ((long)&_SDL_JoyHatEvent.value) - ((long)start);
        data[6] = ((long)&_SDL_JoyHatEvent.padding1) - ((long)start);

        PascalCheckRecord_SDL_JoyHatEvent(data);
        printf("    Done... SDL_JoyHatEvent\n");
    }
    
    void c_check_Record_SDL_JoyButtonEvent() 
    {
        SDL_JoyButtonEvent _SDL_JoyButtonEvent;
        int data[7];
        void *start = &_SDL_JoyButtonEvent;
        data[0] = sizeof(SDL_JoyButtonEvent);
        
        printf("Checking SDL_JoyButtonEvent...\n");
        data[1] = ((long)&_SDL_JoyButtonEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_JoyButtonEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_JoyButtonEvent.which) - ((long)start);
        data[4] = ((long)&_SDL_JoyButtonEvent.button) - ((long)start);
        data[5] = ((long)&_SDL_JoyButtonEvent.state) - ((long)start);
        data[6] = ((long)&_SDL_JoyButtonEvent.padding1) - ((long)start);

        PascalCheckRecord_SDL_JoyButtonEvent(data);
        printf("    Done... SDL_JoyButtonEvent\n");
    }
    
    void c_check_Record_SDL_TouchFingerEvent() 
    {
        SDL_TouchFingerEvent _SDL_TouchFingerEvent;
        int data[15];
        void *start = &_SDL_TouchFingerEvent;
        data[0] = sizeof(SDL_TouchFingerEvent);
        
        printf("Checking SDL_TouchFingerEvent...\n");
        data[1] = ((long)&_SDL_TouchFingerEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_TouchFingerEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_TouchFingerEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_TouchFingerEvent.touchId) - ((long)start);
        data[5] = ((long)&_SDL_TouchFingerEvent.fingerId) - ((long)start);
        data[6] = ((long)&_SDL_TouchFingerEvent.state) - ((long)start);
        data[7] = ((long)&_SDL_TouchFingerEvent.padding1) - ((long)start);
        data[8] = ((long)&_SDL_TouchFingerEvent.padding2) - ((long)start);
        data[9] = ((long)&_SDL_TouchFingerEvent.padding3) - ((long)start);
        data[10] = ((long)&_SDL_TouchFingerEvent.x) - ((long)start);
        data[11] = ((long)&_SDL_TouchFingerEvent.y) - ((long)start);
        data[12] = ((long)&_SDL_TouchFingerEvent.dx) - ((long)start);
        data[13] = ((long)&_SDL_TouchFingerEvent.dy) - ((long)start);
        data[14] = ((long)&_SDL_TouchFingerEvent.pressure) - ((long)start);

        PascalCheckRecord_SDL_TouchFingerEvent(data);
        printf("    Done... SDL_TouchFingerEvent\n");
    }
    
    void c_check_Record_SDL_TouchButtonEvent() 
    {
        SDL_TouchButtonEvent _SDL_TouchButtonEvent;
        int data[9];
        void *start = &_SDL_TouchButtonEvent;
        data[0] = sizeof(SDL_TouchButtonEvent);
        
        printf("Checking SDL_TouchButtonEvent...\n");
        data[1] = ((long)&_SDL_TouchButtonEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_TouchButtonEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_TouchButtonEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_TouchButtonEvent.touchId) - ((long)start);
        data[5] = ((long)&_SDL_TouchButtonEvent.state) - ((long)start);
        data[6] = ((long)&_SDL_TouchButtonEvent.button) - ((long)start);
        data[7] = ((long)&_SDL_TouchButtonEvent.padding1) - ((long)start);
        data[8] = ((long)&_SDL_TouchButtonEvent.padding2) - ((long)start);

        PascalCheckRecord_SDL_TouchButtonEvent(data);
        printf("    Done... SDL_TouchButtonEvent\n");
    }
    
    void c_check_Record_SDL_MultiGestureEvent() 
    {
        SDL_MultiGestureEvent _SDL_MultiGestureEvent;
        int data[11];
        void *start = &_SDL_MultiGestureEvent;
        data[0] = sizeof(SDL_MultiGestureEvent);
        
        printf("Checking SDL_MultiGestureEvent...\n");
        data[1] = ((long)&_SDL_MultiGestureEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_MultiGestureEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_MultiGestureEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_MultiGestureEvent.touchId) - ((long)start);
        data[5] = ((long)&_SDL_MultiGestureEvent.dTheta) - ((long)start);
        data[6] = ((long)&_SDL_MultiGestureEvent.dDist) - ((long)start);
        data[7] = ((long)&_SDL_MultiGestureEvent.x) - ((long)start);
        data[8] = ((long)&_SDL_MultiGestureEvent.y) - ((long)start);
        data[9] = ((long)&_SDL_MultiGestureEvent.numFingers) - ((long)start);
        data[10] = ((long)&_SDL_MultiGestureEvent.padding) - ((long)start);

        PascalCheckRecord_SDL_MultiGestureEvent(data);
        printf("    Done... SDL_MultiGestureEvent\n");
    }
    
    void c_check_Record_SDL_DollarGestureEvent() 
    {
        SDL_DollarGestureEvent _SDL_DollarGestureEvent;
        int data[8];
        void *start = &_SDL_DollarGestureEvent;
        data[0] = sizeof(SDL_DollarGestureEvent);
        
        printf("Checking SDL_DollarGestureEvent...\n");
        data[1] = ((long)&_SDL_DollarGestureEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_DollarGestureEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_DollarGestureEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_DollarGestureEvent.touchId) - ((long)start);
        data[5] = ((long)&_SDL_DollarGestureEvent.gestureId) - ((long)start);
        data[6] = ((long)&_SDL_DollarGestureEvent.numFingers) - ((long)start);
        data[7] = ((long)&_SDL_DollarGestureEvent.error) - ((long)start);

        PascalCheckRecord_SDL_DollarGestureEvent(data);
        printf("    Done... SDL_DollarGestureEvent\n");
    }
    
    void c_check_Record_SDL_DropEvent() 
    {
        SDL_DropEvent _SDL_DropEvent;
        int data[4];
        void *start = &_SDL_DropEvent;
        data[0] = sizeof(SDL_DropEvent);
        
        printf("Checking SDL_DropEvent...\n");
        data[1] = ((long)&_SDL_DropEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_DropEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_DropEvent.file) - ((long)start);

        PascalCheckRecord_SDL_DropEvent(data);
        printf("    Done... SDL_DropEvent\n");
    }
    
    void c_check_Record_SDL_QuitEvent() 
    {
        SDL_QuitEvent _SDL_QuitEvent;
        int data[3];
        void *start = &_SDL_QuitEvent;
        data[0] = sizeof(SDL_QuitEvent);
        
        printf("Checking SDL_QuitEvent...\n");
        data[1] = ((long)&_SDL_QuitEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_QuitEvent.timestamp) - ((long)start);

        PascalCheckRecord_SDL_QuitEvent(data);
        printf("    Done... SDL_QuitEvent\n");
    }
    
    void c_check_Record_SDL_UserEvent() 
    {
        SDL_UserEvent _SDL_UserEvent;
        int data[7];
        void *start = &_SDL_UserEvent;
        data[0] = sizeof(SDL_UserEvent);
        
        printf("Checking SDL_UserEvent...\n");
        data[1] = ((long)&_SDL_UserEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_UserEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_UserEvent.windowID) - ((long)start);
        data[4] = ((long)&_SDL_UserEvent.code) - ((long)start);
        data[5] = ((long)&_SDL_UserEvent.data1) - ((long)start);
        data[6] = ((long)&_SDL_UserEvent.data2) - ((long)start);

        PascalCheckRecord_SDL_UserEvent(data);
        printf("    Done... SDL_UserEvent\n");
    }
    
    void c_check_Record_SDL_SysWMEvent() 
    {
        SDL_SysWMEvent _SDL_SysWMEvent;
        int data[4];
        void *start = &_SDL_SysWMEvent;
        data[0] = sizeof(SDL_SysWMEvent);
        
        printf("Checking SDL_SysWMEvent...\n");
        data[1] = ((long)&_SDL_SysWMEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_SysWMEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_SysWMEvent.msg) - ((long)start);

        PascalCheckRecord_SDL_SysWMEvent(data);
        printf("    Done... SDL_SysWMEvent\n");
    }
    
    void c_check_Record_SDL_ActiveEvent() 
    {
        SDL_ActiveEvent _SDL_ActiveEvent;
        int data[5];
        void *start = &_SDL_ActiveEvent;
        data[0] = sizeof(SDL_ActiveEvent);
        
        printf("Checking SDL_ActiveEvent...\n");
        data[1] = ((long)&_SDL_ActiveEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_ActiveEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_ActiveEvent.gain) - ((long)start);
        data[4] = ((long)&_SDL_ActiveEvent.state) - ((long)start);

        PascalCheckRecord_SDL_ActiveEvent(data);
        printf("    Done... SDL_ActiveEvent\n");
    }
    
    void c_check_Record_SDL_ResizeEvent() 
    {
        SDL_ResizeEvent _SDL_ResizeEvent;
        int data[5];
        void *start = &_SDL_ResizeEvent;
        data[0] = sizeof(SDL_ResizeEvent);
        
        printf("Checking SDL_ResizeEvent...\n");
        data[1] = ((long)&_SDL_ResizeEvent.type) - ((long)start);
        data[2] = ((long)&_SDL_ResizeEvent.timestamp) - ((long)start);
        data[3] = ((long)&_SDL_ResizeEvent.w) - ((long)start);
        data[4] = ((long)&_SDL_ResizeEvent.h) - ((long)start);

        PascalCheckRecord_SDL_ResizeEvent(data);
        printf("    Done... SDL_ResizeEvent\n");
    }
    
    void c_check_Record_SDL_Event() 
    {
        SDL_Event _SDL_Event;
        int data[23];
        void *start = &_SDL_Event;
        data[0] = sizeof(SDL_Event);
        
        printf("Checking SDL_Event...\n");
        data[1] = ((long)&_SDL_Event.type) - ((long)start);
        data[2] = ((long)&_SDL_Event.window) - ((long)start);
        data[3] = ((long)&_SDL_Event.key) - ((long)start);
        data[4] = ((long)&_SDL_Event.edit) - ((long)start);
        data[5] = ((long)&_SDL_Event.text) - ((long)start);
        data[6] = ((long)&_SDL_Event.motion) - ((long)start);
        data[7] = ((long)&_SDL_Event.button) - ((long)start);
        data[8] = ((long)&_SDL_Event.wheel) - ((long)start);
        data[9] = ((long)&_SDL_Event.jaxis) - ((long)start);
        data[10] = ((long)&_SDL_Event.jball) - ((long)start);
        data[11] = ((long)&_SDL_Event.jhat) - ((long)start);
        data[12] = ((long)&_SDL_Event.jbutton) - ((long)start);
        data[13] = ((long)&_SDL_Event.quit) - ((long)start);
        data[14] = ((long)&_SDL_Event.user) - ((long)start);
        data[15] = ((long)&_SDL_Event.syswm) - ((long)start);
        data[16] = ((long)&_SDL_Event.tfinger) - ((long)start);
        data[17] = ((long)&_SDL_Event.tbutton) - ((long)start);
        data[18] = ((long)&_SDL_Event.mgesture) - ((long)start);
        data[19] = ((long)&_SDL_Event.dgesture) - ((long)start);
        data[20] = ((long)&_SDL_Event.drop) - ((long)start);
        data[21] = ((long)&_SDL_Event.active) - ((long)start);
        data[22] = ((long)&_SDL_Event.resize) - ((long)start);

        PascalCheckRecord_SDL_Event(data);
        printf("    Done... SDL_Event\n");
    }
    
    void c_check_Record_SDL_RendererInfo() 
    {
        SDL_RendererInfo _SDL_RendererInfo;
        int data[7];
        void *start = &_SDL_RendererInfo;
        data[0] = sizeof(SDL_RendererInfo);
        
        printf("Checking SDL_RendererInfo...\n");
        data[1] = ((long)&_SDL_RendererInfo.name) - ((long)start);
        data[2] = ((long)&_SDL_RendererInfo.flags) - ((long)start);
        data[3] = ((long)&_SDL_RendererInfo.num_texture_formats) - ((long)start);
        data[4] = ((long)&_SDL_RendererInfo.texture_formats) - ((long)start);
        data[5] = ((long)&_SDL_RendererInfo.max_texture_width) - ((long)start);
        data[6] = ((long)&_SDL_RendererInfo.max_texture_height) - ((long)start);

        PascalCheckRecord_SDL_RendererInfo(data);
        printf("    Done... SDL_RendererInfo\n");
    }
    
    void c_check_Record_SDL_version() 
    {
        SDL_version _SDL_version;
        int data[4];
        void *start = &_SDL_version;
        data[0] = sizeof(SDL_version);
        
        printf("Checking SDL_version...\n");
        data[1] = ((long)&_SDL_version.major) - ((long)start);
        data[2] = ((long)&_SDL_version.minor) - ((long)start);
        data[3] = ((long)&_SDL_version.patch) - ((long)start);

        PascalCheckRecord_SDL_version(data);
        printf("    Done... SDL_version\n");
    }
    
    void c_check_Record_SDL_VideoInfo() 
    {
        SDL_VideoInfo _SDL_VideoInfo;
        int data[6];
        void *start = &_SDL_VideoInfo;
        data[0] = sizeof(SDL_VideoInfo);
        
        printf("Checking SDL_VideoInfo...\n");
        data[1] = ((long)&_SDL_VideoInfo) - ((long)start);
        data[2] = ((long)&_SDL_VideoInfo.video_mem) - ((long)start);
        data[3] = ((long)&_SDL_VideoInfo.vfmt) - ((long)start);
        data[4] = ((long)&_SDL_VideoInfo.current_w) - ((long)start);
        data[5] = ((long)&_SDL_VideoInfo.current_h) - ((long)start);

        PascalCheckRecord_SDL_VideoInfo(data);
        printf("    Done... SDL_VideoInfo\n");
    }
    
    void c_check_Record_SDL_Overlay() 
    {
        SDL_Overlay _SDL_Overlay;
        int data[10];
        void *start = &_SDL_Overlay;
        data[0] = sizeof(SDL_Overlay);
        
        printf("Checking SDL_Overlay...\n");
        data[1] = ((long)&_SDL_Overlay.format) - ((long)start);
        data[2] = ((long)&_SDL_Overlay.w) - ((long)start);
        data[3] = ((long)&_SDL_Overlay.h) - ((long)start);
        data[4] = ((long)&_SDL_Overlay.planes) - ((long)start);
        data[5] = ((long)&_SDL_Overlay.pitches) - ((long)start);
        data[6] = ((long)&_SDL_Overlay.pixels) - ((long)start);
        data[7] = ((long)&_SDL_Overlay.hwfuncs) - ((long)start);
        data[8] = ((long)&_SDL_Overlay.hwdata) - ((long)start);
        data[9] = ((long)&_SDL_Overlay.hwdata) + sizeof(void*) - ((long)start);

        PascalCheckRecord_SDL_Overlay(data);
        printf("    Done... SDL_Overlay\n");
    }
    
int main()
{
   c_check_enum_SDL_bool();
   c_check_enum_SDL_DUMMY_ENUM();
   c_check_enum_SDL_assert_state();
   c_check_enum_SDL_errorcode();
   c_check_enum_SDL_ThreadPriority();
   c_check_enum_SDL_AudioStatus();
   c_check_enum_SDL_BlendMode();
   c_check_enum_SDL_WindowFlags();
   c_check_enum_SDL_WindowEventID();
   c_check_enum_SDL_GLattr();
   c_check_enum_SDL_Scancode();
   c_check_enum_SDL_Keymod();
   c_check_enum_SDL_EventType();
   c_check_enum_SDL_eventaction();
   c_check_enum_SDL_HintPriority();
   c_check_enum_SDL_LogPriority();
   c_check_enum_SDL_PowerState();
   c_check_enum_SDL_RendererFlags();
   c_check_enum_SDL_TextureAccess();
   c_check_enum_SDL_TextureModulate();
   c_check_enum_SDL_GrabMode();
   c_check_Record_SDL_assert_data();
   c_check_Record_SDL_atomic_t();
   c_check_Record_SDL_RWops();
   c_check_Record_SDL_AudioSpec();
   c_check_Record_SDL_AudioCVT();
   c_check_Record_SDL_Color();
   c_check_Record_SDL_Palette();
   c_check_Record_SDL_PixelFormat();
   c_check_Record_SDL_Point();
   c_check_Record_SDL_Rect();
   c_check_Record_SDL_Surface();
   c_check_Record_SDL_DisplayMode();
   c_check_Record_SDL_Keysym();
   c_check_Record_SDL_Finger();
   c_check_Record_SDL_Touch();
   c_check_Record_SDL_WindowEvent();
   c_check_Record_SDL_KeyboardEvent();
   c_check_Record_SDL_TextEditingEvent();
   c_check_Record_SDL_TextInputEvent();
   c_check_Record_SDL_MouseMotionEvent();
   c_check_Record_SDL_MouseButtonEvent();
   c_check_Record_SDL_MouseWheelEvent();
   c_check_Record_SDL_JoyAxisEvent();
   c_check_Record_SDL_JoyBallEvent();
   c_check_Record_SDL_JoyHatEvent();
   c_check_Record_SDL_JoyButtonEvent();
   c_check_Record_SDL_TouchFingerEvent();
   c_check_Record_SDL_TouchButtonEvent();
   c_check_Record_SDL_MultiGestureEvent();
   c_check_Record_SDL_DollarGestureEvent();
   c_check_Record_SDL_DropEvent();
   c_check_Record_SDL_QuitEvent();
   c_check_Record_SDL_UserEvent();
   c_check_Record_SDL_SysWMEvent();
   c_check_Record_SDL_ActiveEvent();
   c_check_Record_SDL_ResizeEvent();
   c_check_Record_SDL_Event();
   c_check_Record_SDL_RendererInfo();
   c_check_Record_SDL_version();
   c_check_Record_SDL_VideoInfo();
   c_check_Record_SDL_Overlay(); 
   return 0;
}