SGSDK.NET/lib/SGSDK.o
SGSDK.NET/lib/SGSDK_Core.o
SGSDK.NET/lib/SGSDK_Input.o
SGSDK.NET/lib/SGSDK_Audio.o
SGSDK.NET/lib/SGSDK_Font.o
SGSDK.NET/lib/SGSDK_Physics.o
SGSDK.NET/lib/SGSDK_Graphics.o
SGSDK.NET/lib/sdl_mixer.o
SGSDK.NET/lib/sdl.o
SGSDK.NET/lib/sdl_image.o
SGSDK.NET/lib/sdl_ttf.o
SGSDK.NET/lib/SGSDK_Camera.o
SGSDK.NET/lib/SGSDK_Shapes.o
SGSDK.NET/lib/SGSDK_MappyLoader.o
SGSDK.NET/lib/SDLEventProcessing.o
